### ISSUE TITLE
Alex's Delight causing entities to disappear (Forge 1.18.2)

### ISSUE THREAD

**Issue by XlosVSM** [Nyancatpig/Alexs-Delight#8]
**Mods used (latest versions)**

- [Create (by simibubi)](https://www.curseforge.com/minecraft/mc-mods/create) 
- [AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin) 
- [Backpacked (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/backpacked) 
- [Spyglass Improvements: Zoom, Quick Access... [Fabric/Forge] (by Im_JC52)](https://www.curseforge.com/minecraft/mc-mods/spyglass-improvements) 
- [Clickable advancements[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/clickable-advancements) 
- [Village Bell Recipe (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/village-bell-recipe) 
- [Farmer's Delight (by vectorwing)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight) 
- [Clear Glass with Connected Textures! [16x] (by Dnator)](https://www.curseforge.com/minecraft/texture-packs/clear-glass-pack)
- [Almost Unified (by AlmostReliable)](https://www.curseforge.com/minecraft/mc-mods/almost-unified)
- [TexTrue's Rubidium Options (by TexTrue)](https://www.curseforge.com/minecraft/mc-mods/textrues-rubidium-options)
- [Spice of Life: Carrot Edition (by lordcazsius)](https://www.curseforge.com/minecraft/mc-mods/spice-of-life-carrot-edition)
- [Slightly Improved Font (32x) (by LatvianModder)](https://www.curseforge.com/minecraft/texture-packs/slightly-improved-font)
- [Catalogue (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/catalogue)
- [Alex's Mobs (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/alexs-mobs)
- [HT's TreeChop (by hammertater)](https://www.curseforge.com/minecraft/mc-mods/treechop)
- [Game Menu Remove GFARB (by morimori0317)](https://www.curseforge.com/minecraft/mc-mods/game-menu-remove-gfarb)
- [Mod Name Tooltip (by mezz)](https://www.curseforge.com/minecraft/mc-mods/mod-name-tooltip)
- [Iceberg [Forge] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/iceberg)
- [Game Menu Mod Option [Forge] (by morimori0317)](https://www.curseforge.com/minecraft/mc-mods/gamemenumodoption)
- [No Recipe Book Reborn (by IronFractal)](https://www.curseforge.com/minecraft/mc-mods/no-recipe-book-reborn)
- [Akashic Tome (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/akashic-tome)
- [Just Another Rotten Flesh to Leather Mod (by alexdaum1)](https://www.curseforge.com/minecraft/mc-mods/just-another-rotten-flesh-to-leather-mod)
- [Create Style Modded Compats (by wedge1453)](https://www.curseforge.com/minecraft/texture-packs/create-style-modded-compats)
- [Better Compatibility Checker (by Gaz_)](https://www.curseforge.com/minecraft/mc-mods/better-compatibility-checker)
- [Citadel (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/citadel)
- [Advancement Plaques [Forge] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/advancement-plaques)
- [Just Enough Painting Previews (JEPP) (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/jepp)
- [Rubidium (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/rubidium)
- [Shutup Experimental Settings! (by Corgi_Taco)](https://www.curseforge.com/minecraft/mc-mods/shutup-experimental-settings)
- [Balm (Forge Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm)
- [Better Advancements (by way2muchnoise)](https://www.curseforge.com/minecraft/mc-mods/better-advancements)
- [AutoRegLib (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/autoreglib)
- [Starlight (Forge) (by Spottedstar)](https://www.curseforge.com/minecraft/mc-mods/starlight-forge)
- [JEI Integration (by SnowShock35)](https://www.curseforge.com/minecraft/mc-mods/jei-integration)
- [Villager Names (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/villager-names)
- [Every Compat (Wood Good) (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/every-compat)
- [Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
- [Nether's Delight (by lumpazl)](https://www.curseforge.com/minecraft/mc-mods/nethers-delight)
- [Jade Addons (Forge) (by Snownee_)](https://www.curseforge.com/minecraft/mc-mods/jade-addons)
- [Just Player Heads (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/just-player-heads)
- [Default Options (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/default-options)
- [Rubidium Extra (by dimadencep)](https://www.curseforge.com/minecraft/mc-mods/rubidium-extra)
- [HT's TreeChop - Jade Plugin (by hammertater)](https://www.curseforge.com/minecraft/mc-mods/treechopjade)
- [Just Enough Professions (JEP) (by Mrbysco)](https://www.curseforge.com/minecraft/mc-mods/just-enough-professions-jep)
- [AttributeFix (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/attributefix)
- [Oculus (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/oculus)
- [Collective (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/collective)
- [Just Mob Heads (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/just-mob-heads)
- [Iris & Oculus Flywheel Compat (by leon_mout)](https://www.curseforge.com/minecraft/mc-mods/iris-flywheel-compat)
- [Canary (by AbdElAziz333)](https://www.curseforge.com/minecraft/mc-mods/canary)
- [Magnesium/Rubidium Dynamic Lights (by TeamDeusVult)](https://www.curseforge.com/minecraft/mc-mods/dynamiclights-reforged)
- [Embellished Stone (Advancement Plaques) (by Grend_G)](https://www.curseforge.com/minecraft/texture-packs/embellished-stone-advancement-plaques)
- [I Know What I'm Doing (IKWID) (by HeckinChloe)](https://www.curseforge.com/minecraft/mc-mods/i-know-what-im-doing)
- [Ecologics (by SameDifferent)](https://www.curseforge.com/minecraft/mc-mods/ecologics)
- [Just Enough Effect Descriptions (JEED) (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/just-enough-effect-descriptions-jeed)
- [Alex's Delight (by NCP_Bails)](https://www.curseforge.com/minecraft/mc-mods/alexs-delight)
- [Flywheel (by jozufozu)](https://www.curseforge.com/minecraft/mc-mods/flywheel)
- [Magnesium/Rubidium Extras (by TeamDeusVult)](https://www.curseforge.com/minecraft/mc-mods/magnesium-extras)
- [Just Enough Resources (JER) (by way2muchnoise)](https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer)
- [Quark (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/quark)
- [Jade 🔍 (by Snownee_)](https://www.curseforge.com/minecraft/mc-mods/jade)
- [Goblin Traders (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/goblin-traders)
- [JEI Enchantment Info (by Phylogeny)](https://www.curseforge.com/minecraft/mc-mods/jei-enchantment-info)
- [Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)
- [Diet (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/diet)
- [Moonlight Lib (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/selene)
- [No Recipe Advancements (by MutantGumdrop)](https://www.curseforge.com/minecraft/mc-mods/no-recipe-advancements)

**Comment by Nyancatpig** [comment]
Do you mean that sometimes all entities are invisible for no discernible reason? (Inclusing yourself)
Because I’ve encounterrd that issue as well, and I don’t think it was Alex’s Delight causing it.

**Comment by XlosVSM** [comment]
> 

Yes, but I removed Alex's Delight and it fixed it
